export const RESPONSE_CODE_SERVER_FAILURE = 500;
export const RESPONSE_CODE_SUCCESS = 200;
export const RESPONSE_CODE_NOT_FOUND = 404;

export const RESPONSE_TYPE_JSON = "RESPONSE_TYPE_JSON";
export const RESPONSE_TYPE_TEXT = "RESPONSE_TYPE_TEXT";

export const MONGOOSE_DOCUMENT_VERSION_KEY = "__v";

export const ERROR_CODE_FILE_NOT_FOUND = "ENOENT";